pipeline {

    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                dir('countopedia') {
                    bat 'npm ci'
                }
            }
        }

        stage('Build') {
            steps {
                dir('countopedia') {
                    bat 'npm run build'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('countopedia') {
                    bat 'docker build -t countopedia:%BUILD_NUMBER% .'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {

                    if (env.BRANCH_NAME == 'dev') {

                        bat '''
                            docker stop countopedia-dev || exit /b 0
                            docker rm countopedia-dev || exit /b 0
                            docker run -d --name countopedia-dev -p 8081:80 countopedia:%BUILD_NUMBER%
                        '''

                    }
                }
            }
        }
    }
}
