pipeline {
    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                dir('countopedia') {
                    bat 'npm ci'
                }
            }
        }

        stage('Build') {
            steps {
                dir('countopedia') {
                    bat 'npm run build'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('countopedia') {
                    script {

                        if (env.BRANCH_NAME == 'dev') {

                            bat 'docker build -t countopedia:dev-%BUILD_NUMBER% .'

                        }
                        else if (env.BRANCH_NAME == 'test') {

                            bat 'docker build -t countopedia:test-%BUILD_NUMBER% .'

                        }

                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {

                    if (env.BRANCH_NAME == 'dev') {

                        bat '''
                            docker stop countopedia-dev || echo Container does not exist
                            docker rm countopedia-dev || echo Container does not exist
                            docker run -d --name countopedia-dev -p 8081:80 countopedia:dev-%BUILD_NUMBER%
                        '''

                    }
                    else if (env.BRANCH_NAME == 'test') {

                        bat '''
                            docker stop countopedia-test || echo Container does not exist
                            docker rm countopedia-test || echo Container does not exist
                            docker run -d --name countopedia-test -p 8082:80 countopedia:test-%BUILD_NUMBER%
                        '''

                    }

                }
            }
        }

    }
}
